//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Data.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioImage
    {
        public string filename { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string category { get; set; }
        public string id { get; set; }
        public Nullable<int> ordinal { get; set; }
    
        public virtual PortfolioTag PortfolioTag { get; set; }
    }
}
